name = "crowdvine-preview"
compatibility_date = "2024-01-01"

[env.production]
# Production environment variables will be set in Cloudflare Pages dashboard

[build]
command = "npm run build"
publish = "out"

[[build.environment_variables]]
NODE_ENV = "production"
