export interface TopWine {
  rank: number;
  wine: string;
  producer: string;
  region: string;
  country: string;
  type: string;
  grapes: string;
  description?: string;
  descriptionEn?: string;
}

export const TOP_100_WINES: TopWine[] = [
  {
    rank: 1,
    wine: "Arbois-Pupillin Savagnin",
    producer: "Pierre Overnoy / Emmanuel Houillon",
    region: "Arbois-Pupillin, Jura",
    country: "Frankrike",
    type: "Vitt",
    grapes: "Savagnin",
    description:
      "Det här är flaskan som gjorde naturvin till något mer än en idé. Overnoys Savagnin vinifieras ouillé — fatet fylls på så att inget jästtäcke bildas — vilket bryter mot Juras hela tradition. Utan tillsatt svavel och utan skyddande voile borde vinet ha oxiderat inom några år. Istället åldras det i decennier och har blivit måttstocken för hela rörelsen.",
    descriptionEn:
      "This is the bottle that made natural wine more than an idea. Overnoy's Savagnin is vinified ouillé — the barrel topped up so no veil of yeast forms — which breaks with the whole Jura tradition. Without added sulphur and without a protective voile the wine should have oxidised within a few years. Instead it ages for decades and has become the benchmark for the entire movement.",
  },
  {
    rank: 2,
    wine: "Cornas Chaillot",
    producer: "Thierry Allemand",
    region: "Cornas, Rhône",
    country: "Frankrike",
    type: "Rött",
    grapes: "Syrah",
    description:
      "Chaillot kommer från yngre stockar än Allemands andra cuvée men är på inget sätt ett andravin. Terrasserna av granit ger en Syrah med svartpeppar, violer och en salt mineralitet under frukten. Vinet är strukturerat och lagringsbart utan att någonsin bli tungt.",
    descriptionEn:
      "Chaillot comes from younger vines than Allemand's other cuvée but is in no sense a second wine. The granite terraces give a Syrah with black pepper, violets and a saline minerality beneath the fruit. The wine is structured and age-worthy without ever becoming heavy.",
  },
  {
    rank: 3,
    wine: "Ribolla Gialla Anfora",
    producer: "Gravner",
    region: "Friuli Collio",
    country: "Italien",
    type: "Orange",
    grapes: "Ribolla Gialla",
    description:
      "Efter Gravners resa till Georgien 1997 började han vinifiera i qvevri nedgrävda i källargolvet. Ribolla Gialla får månader av skalkontakt utan temperaturkontroll och lagras därefter i stora fat i flera år innan release. Resultatet är bärnstensfärgat, tanninrikt och närmast te-liknande i aromatiken.",
    descriptionEn:
      "After Gravner's 1997 trip to Georgia he began vinifying in qvevri buried in the cellar floor. Ribolla Gialla gets months of skin contact without temperature control and is then aged in large casks for several years before release. The result is amber, tannic and almost tea-like in its aromatics.",
  },
  {
    rank: 4,
    wine: "Les Chalasses Vieilles Vignes",
    producer: "Jean-François Ganevat",
    region: "Côtes du Jura",
    country: "Frankrike",
    type: "Vitt",
    grapes: "Chardonnay",
    description:
      "Från gamla stockar på märgeljord i Rotalier, planterade av Ganevats farfar. Vinet är vinifierat ouillé med lång elevage och har den kombination av spänst och djup som gjort Ganevat till en av naturvinets mest jagade producenter.",
    descriptionEn:
      "From old vines on marl soil in Rotalier, planted by Ganevat's grandfather. The wine is vinified ouillé with long élevage and has the combination of tension and depth that has made Ganevat one of natural wine's most hunted producers.",
  },
  {
    rank: 5,
    wine: "Substance",
    producer: "Jacques Selosse",
    region: "Champagne",
    country: "Frankrike",
    type: "Champagne",
    grapes: "Chardonnay",
    description:
      "Substance görs i ett solera-system som Anselme Selosse startade 1986 och som därför innehåller vin från varje årgång sedan dess. Chardonnay från Avize, fatjäst och oxidativt behandlad, ger en champagne som mer liknar en sherry i sin komplexitet än en traditionell brut.",
    descriptionEn:
      "Substance is made in a solera system Anselme Selosse started in 1986, which means it contains wine from every vintage since. Chardonnay from Avize, barrel-fermented and oxidatively handled, gives a champagne closer to sherry in its complexity than to a traditional brut.",
  },
  {
    rank: 6,
    wine: "Rkatsiteli",
    producer: "Pheasant's Tears",
    region: "Kakheti, Georgien",
    country: "Georgien",
    type: "Orange",
    grapes: "Rkatsiteli",
    description:
      "Rkatsiteli är Georgiens mest odlade vita druva och här vinifieras den precis som den gjorts i åtta tusen år: hela klasar med skal och skaft i qvevri nedgrävda i marken, utan tillsatser. Vinet doftar av torkade aprikoser, valnöt och svart te.",
    descriptionEn:
      "Rkatsiteli is Georgia's most planted white grape, and here it is vinified exactly as it has been for eight thousand years: whole clusters with skins and stems in qvevri buried in the ground, without additives. The wine smells of dried apricot, walnut and black tea.",
  },
  {
    rank: 7,
    wine: "Cornas Reynard",
    producer: "Thierry Allemand",
    region: "Cornas, Rhône",
    country: "Frankrike",
    type: "Rött",
    grapes: "Syrah",
    description:
      "Reynard kommer från Allemands äldsta stockar på de branta granitterrasserna och är hans mest strukturerade vin. Där Chaillot är omedelbar är Reynard sluten i ungdomen och kräver år. Med tid utvecklas den mot rök, oliv, blod och violer.",
    descriptionEn:
      "Reynard comes from Allemand's oldest vines on the steep granite terraces and is his most structured wine. Where Chaillot is immediate, Reynard is closed in youth and demands years. With time it develops towards smoke, olive, blood and violets.",
  },
  {
    rank: 8,
    wine: "Entre Deux Bleus",
    producer: "Domaine des Miroirs / Kenjiro Kagami",
    region: "Côtes du Jura",
    country: "Frankrike",
    type: "Vitt",
    grapes: "Savagnin",
    description:
      "Kagamis viner produceras i så små volymer att de knappt når marknaden. Entre Deux Bleus är hans mest omtalade cuvée — ett vitt Jura-vin med en klarhet och spänst som får de flesta jämförelser att kännas otillräckliga.",
    descriptionEn:
      "Kagami's wines are produced in such small volumes that they barely reach the market. Entre Deux Bleus is his most talked-about cuvée — a white Jura wine with a clarity and tension that makes most comparisons feel inadequate.",
  },
  {
    rank: 9,
    wine: "Oslavje",
    producer: "Radikon",
    region: "Friuli Collio",
    country: "Italien",
    type: "Orange",
    grapes: "Chardonnay, Sauvignon, Pinot Grigio",
    description:
      "Oslavje är en blandning av Chardonnay, Sauvignon och Pinot Grigio med lång skalkontakt i stora slavonska fat, utan tillsatt svavel och utan filtrering. Vinet är djupt bärnstensfärgat med tanniner som ett rött vin.",
    descriptionEn:
      "Oslavje is a blend of Chardonnay, Sauvignon and Pinot Grigio with long skin contact in large Slavonian casks, without added sulphur and without filtration. The wine is deeply amber with tannins like a red wine.",
  },
  {
    rank: 10,
    wine: "Clos Rougeard Le Bourg",
    producer: "Clos Rougeard (Foucault)",
    region: "Saumur-Champigny, Loire",
    country: "Frankrike",
    type: "Rött",
    grapes: "Cabernet Franc",
    description:
      "Le Bourg kommer från en liten parcell med gamla stockar och lagras i nya fat — ovanligt för naturvin, men bröderna Foucault följde aldrig någons regler utom sina egna. Vinet visade världen att Cabernet Franc från Loire kunde stå bredvid de största vinerna från Bordeaux och Bourgogne.",
    descriptionEn:
      "Le Bourg comes from a small parcel of old vines and is aged in new barrels — unusual for natural wine, but the Foucault brothers never followed anyone's rules but their own. The wine showed the world that Cabernet Franc from the Loire could stand beside the greatest wines of Bordeaux and Burgundy.",
  },
  {
    rank: 11,
    wine: "Arbois-Pupillin Chardonnay",
    producer: "Pierre Overnoy / Emmanuel Houillon",
    region: "Arbois-Pupillin, Jura",
    country: "Frankrike",
    type: "Vitt",
    grapes: "Chardonnay",
    description:
      "Samma kompromisslösa metod som Savagninen men på Chardonnay. Vinet har en salt, nästan jodig mineralitet och åldras lika obegripligt länge för att vara helt utan tillsatt svavel.",
    descriptionEn:
      "The same uncompromising method as the Savagnin but on Chardonnay. The wine has a saline, almost iodine minerality and ages just as improbably long for something made entirely without added sulphur.",
  },
  {
    rank: 12,
    wine: "Morgon Côte du Py",
    producer: "Jean Foillard",
    region: "Beaujolais",
    country: "Frankrike",
    type: "Rött",
    grapes: "Gamay",
    description:
      "Från den blå granitkullen som är Morgons bästa läge. Foillards version är djup, jordig och strukturerad — det vin som mer än något annat visade att Gamay kan vara seriöst.",
    descriptionEn:
      "From the blue granite hill that is Morgon's finest site. Foillard's version is deep, earthy and structured — the wine that more than any other showed Gamay could be serious.",
  },
  {
    rank: 13,
    wine: "Breg Anfora",
    producer: "Gravner",
    region: "Friuli Collio",
    country: "Italien",
    type: "Orange",
    grapes: "Sauvignon, Chardonnay, Pinot Grigio, Riesling",
    description:
      "Gravners andra amforavin, en blandning av Chardonnay, Sauvignon, Pinot Grigio och Riesling Italico. Djupare och mer oxidativt än Ribollan, med en fenolisk struktur som kräver mat.",
    descriptionEn:
      "Gravner's second amphora wine, a blend of Chardonnay, Sauvignon, Pinot Grigio and Riesling Italico. Deeper and more oxidative than the Ribolla, with a phenolic structure that demands food.",
  },
  {
    rank: 14,
    wine: "Cuvée de l'Enfant Terrible",
    producer: "Jean-François Ganevat",
    region: "Côtes du Jura",
    country: "Frankrike",
    type: "Rött",
    grapes: "Poulsard",
    description:
      "Ganevats mest lättillgängliga röda — bleka, doftande Poulsard med hallon, blodapelsin och en nästan genomskinlig kropp. Namnet är ett självporträtt.",
    descriptionEn:
      "Ganevat's most approachable red — pale, perfumed Poulsard with raspberry, blood orange and an almost transparent body. The name is a self-portrait.",
  },
  {
    rank: 15,
    wine: "Initial",
    producer: "Jacques Selosse",
    region: "Champagne",
    country: "Frankrike",
    type: "Champagne",
    grapes: "Chardonnay",
    description:
      "Selosses instegschampagne på Chardonnay från Avize, Cramant och Oger, men \"insteg\" är missvisande. Fatjäst, oxidativ och texturrik — för många den bästa introduktionen till vad grower champagne kan vara.",
    descriptionEn:
      "Selosse's entry-level champagne from Chardonnay grown in Avize, Cramant and Oger, though entry-level is misleading. Barrel-fermented, oxidative and textured — for many the best introduction to what grower champagne can be.",
  },
  {
    rank: 16,
    wine: "Tsitska-Tsolikouri",
    producer: "Ramaz Nikoladze",
    region: "Nakhshirgele, Imereti, Georgien",
    country: "Georgien",
    type: "Orange",
    grapes: "Tsitska, Tsolikouri",
    description:
      "Två inhemska georgiska druvor i qvevri med kortare skalkontakt än Kakheti-traditionen. Lättare och mer floral än östgeorgiska orangeviner — Imeretis egen stil.",
    descriptionEn:
      "Two indigenous Georgian grapes in qvevri with shorter skin contact than the Kakheti tradition. Lighter and more floral than eastern Georgian orange wines — Imereti's own style.",
  },
  {
    rank: 17,
    wine: "I Need the Sun",
    producer: "Domaine des Miroirs / Kenjiro Kagami",
    region: "Côtes du Jura",
    country: "Frankrike",
    type: "Vitt",
    grapes: "Chardonnay",
    description:
      "Kagamis Chardonnay, med samma spröda precision som resten av sortimentet. Namnet är ett av flera som gjort domänet lika känt för sin estetik som för sina viner.",
    descriptionEn:
      "Kagami's Chardonnay, with the same brittle precision as the rest of the range. The name is one of several that have made the domaine as known for its aesthetic as for its wines.",
  },
  {
    rank: 18,
    wine: "Jakot",
    producer: "Radikon",
    region: "Friuli Collio",
    country: "Italien",
    type: "Orange",
    grapes: "Tocai Friulano",
    description:
      "Namnet är Tokaj baklänges — en protest mot EU-förbudet att kalla druvan Tocai Friulano. Vinet är en av de renaste tolkningarna av Friulano med lång skalkontakt.",
    descriptionEn:
      "The name is Tokaj spelled backwards — a protest against the EU ban on calling the grape Tocai Friulano. The wine is one of the purest interpretations of Friulano with long skin contact.",
  },
  {
    rank: 19,
    wine: "Clos Rougeard Les Poyeux",
    producer: "Clos Rougeard (Foucault)",
    region: "Saumur-Champigny, Loire",
    country: "Frankrike",
    type: "Rött",
    grapes: "Cabernet Franc",
    description:
      "Den mer sensuella av Clos Rougeards två stora cuvéer. Där Le Bourg är strukturerad och sluten är Les Poyeux öppen, doftande och nästan bourgognelik i sin finess.",
    descriptionEn:
      "The more sensual of Clos Rougeard's two great cuvées. Where Le Bourg is structured and closed, Les Poyeux is open, perfumed and almost Burgundian in its finesse.",
  },
  {
    rank: 20,
    wine: "Morgon",
    producer: "Marcel Lapierre",
    region: "Beaujolais",
    country: "Frankrike",
    type: "Rött",
    grapes: "Gamay",
    description:
      "Vinet som startade allt i Beaujolais. Lapierres Morgon är saftig, jordig och omedelbar — en mall som hundratals producenter försökt kopiera sedan 1980-talet.",
    descriptionEn:
      "The wine that started everything in Beaujolais. Lapierre's Morgon is juicy, earthy and immediate — a template hundreds of producers have tried to copy since the 1980s.",
  },
  {
    rank: 21,
    wine: "Arbois-Pupillin Ploussard",
    producer: "Pierre Overnoy / Emmanuel Houillon",
    region: "Arbois-Pupillin, Jura",
    country: "Frankrike",
    type: "Rött",
    grapes: "Poulsard",
    description:
      "Blek nästan till rosé, med hallon, järn och en genomskinlighet som är Juras signatur. Ett rött vin som tvingar en att omvärdera vad rött vin kan vara.",
    descriptionEn:
      "Pale almost to rosé, with raspberry, iron and a transparency that is the Jura's signature. A red wine that forces you to reconsider what red wine can be.",
  },
  {
    rank: 22,
    wine: "La Terre Rouge",
    producer: "Jean-Pierre Robinot",
    region: "Chahaignes, Coteaux du Loir, Loire",
    country: "Frankrike",
    type: "Rött",
    grapes: "Pineau d'Aunis",
    description:
      "Robinots tolkning av Loires mest särpräglade röda druva — pepprig, lätt och vild, gjord helt utan svavel.",
    descriptionEn:
      "Robinot's interpretation of the Loire's most distinctive red grape — peppery, light and wild, made entirely without sulphur.",
  },
  {
    rank: 23,
    wine: "Saint-Joseph Rouge",
    producer: "Dard & Ribo",
    region: "Saint-Joseph, Rhône",
    country: "Frankrike",
    type: "Rött",
    grapes: "Syrah",
    description:
      "Motsatsen till norra Rhônes extraherade stil: lätt, saftig, doftande och drickbar ung. Dard & Ribo visade att Syrah inte behöver vara tung för att vara stor.",
    descriptionEn:
      "The opposite of the northern Rhône's extracted style: light, juicy, perfumed and drinkable young. Dard & Ribo showed that Syrah does not need to be heavy to be great.",
  },
  {
    rank: 24,
    wine: "Magma",
    producer: "Frank Cornelissen",
    region: "Contrada Barbabecchi, Etna Nord, Sicilien",
    country: "Italien",
    type: "Rött",
    grapes: "Nerello Mascalese",
    description:
      "Från de högst belägna stockarna på Etnas nordsluttning, vinifierat med minimal intervention. Ett av naturvinets mest kompromisslösa och omdiskuterade viner.",
    descriptionEn:
      "From the highest vines on Etna's northern slope, vinified with minimal intervention. One of natural wine's most uncompromising and most debated wines.",
  },
  {
    rank: 25,
    wine: "Les Grands Teppes Vieilles Vignes",
    producer: "Jean-François Ganevat",
    region: "Côtes du Jura",
    country: "Frankrike",
    type: "Vitt",
    grapes: "Chardonnay",
    description:
      "Gamla stockar på blå märgel, vinifierat ouillé med lång elevage. Ett av de vita viner som bäst visar varför Ganevat blivit en av rörelsens mest jagade producenter.",
    descriptionEn:
      "Old vines on blue marl, vinified ouillé with long élevage. One of the white wines that best shows why Ganevat became one of the movement's most hunted producers.",
  },
  {
    rank: 26,
    wine: "Les Ursules Blanc de Noirs",
    producer: "Roses de Jeanne / Cédric Bouchard",
    region: "Celles-sur-Ource, Aube, Champagne",
    country: "Frankrike",
    type: "Champagne",
    grapes: "Pinot Noir",
    description:
      "En parcell, en druvsort, en årgång — Bouchards princip i praktiken. Pinot Noir från Celles-sur-Ource med låg dosage och en lätthet som är helt hans egen.",
    descriptionEn:
      "One parcel, one variety, one vintage — Bouchard's principle in practice. Pinot Noir from Celles-sur-Ource with low dosage and a lightness entirely his own.",
  },
  {
    rank: 27,
    wine: "Sonorité du Vent",
    producer: "Domaine des Miroirs / Kenjiro Kagami",
    region: "Côtes du Jura",
    country: "Frankrike",
    type: "Vitt",
    grapes: "Savagnin",
    description:
      "Kagamis Savagnin, vinifierad ouillé. Spänstig, salt och nästan spröd — och en av de svåraste flaskorna i hela naturvinsvärlden att hitta.",
    descriptionEn:
      "Kagami's Savagnin, vinified ouillé. Taut, saline and almost brittle — and one of the hardest bottles to find in the entire natural wine world.",
  },
  {
    rank: 28,
    wine: "Ribolla",
    producer: "Radikon",
    region: "Friuli Collio",
    country: "Italien",
    type: "Orange",
    grapes: "Ribolla Gialla",
    description:
      "Radikons rena Ribolla Gialla, med lång skalkontakt i slavonsk ek. Tillsammans med Gravners version det vin som definierade Oslavje som orangevinets huvudstad.",
    descriptionEn:
      "Radikon's pure Ribolla Gialla, with long skin contact in Slavonian oak. Together with Gravner's version, the wine that defined Oslavje as the capital of orange wine.",
  },
  {
    rank: 29,
    wine: "Coulée de Serrant",
    producer: "Nicolas Joly",
    region: "Savennières, Loire",
    country: "Frankrike",
    type: "Vitt",
    grapes: "Chenin Blanc",
    description:
      "En av få franska appellationer som utgörs av en enda vingård, biodynamiskt odlad av Joly sedan 1980-talet. Ett vin som delar åsikter men som ingen ignorerar.",
    descriptionEn:
      "One of few French appellations consisting of a single vineyard, farmed biodynamically by Joly since the 1980s. A wine that divides opinion but which no one ignores.",
  },
  {
    rank: 30,
    wine: "Fleurie",
    producer: "Yvon Métras",
    region: "Beaujolais",
    country: "Frankrike",
    type: "Rött",
    grapes: "Gamay",
    description:
      "Métras arbetar med helklase och nära noll svavel. Hans Fleurie är parfymerad, genomskinlig och elektrisk — och bland de svåraste vinerna att få tag på i regionen.",
    descriptionEn:
      "Métras works with whole clusters and near-zero sulphur. His Fleurie is perfumed, transparent and electric — and among the hardest wines to find in the region.",
  },
  {
    rank: 31,
    wine: "Ploussard Point Barre",
    producer: "Philippe Bornard",
    region: "Arbois-Pupillin, Jura",
    country: "Frankrike",
    type: "Rött",
    grapes: "Poulsard",
  },
  {
    rank: 32,
    wine: "Crozes-Hermitage Rouge",
    producer: "Dard & Ribo",
    region: "Crozes-Hermitage, Rhône",
    country: "Frankrike",
    type: "Rött",
    grapes: "Syrah",
  },
  {
    rank: 33,
    wine: "Ageno",
    producer: "La Stoppa",
    region: "Emilia-Romagna",
    country: "Italien",
    type: "Orange",
    grapes: "Malvasia, Ortrugo",
  },
  {
    rank: 34,
    wine: "Trousseau Les Corvées",
    producer: "Stéphane Tissot",
    region: "Arbois, Jura",
    country: "Frankrike",
    type: "Rött",
    grapes: "Trousseau",
  },
  {
    rank: 35,
    wine: "La Haute-Lemblé Blanc de Blancs",
    producer: "Roses de Jeanne / Cédric Bouchard",
    region: "Celles-sur-Ource, Aube, Champagne",
    country: "Frankrike",
    type: "Champagne",
    grapes: "Chardonnay",
  },
  {
    rank: 36,
    wine: "Châteauneuf-du-Pape Rouge",
    producer: "Château Rayas",
    region: "Châteauneuf-du-Pape, Rhône",
    country: "Frankrike",
    type: "Rött",
    grapes: "Grenache",
  },
  {
    rank: 37,
    wine: "Château-Chalon",
    producer: "Jean Macle",
    region: "Château-Chalon, Jura",
    country: "Frankrike",
    type: "Vitt",
    grapes: "Savagnin",
  },
  {
    rank: 38,
    wine: "Morgon 3.14",
    producer: "Jean Foillard",
    region: "Beaujolais",
    country: "Frankrike",
    type: "Rött",
    grapes: "Gamay",
  },
  {
    rank: 39,
    wine: "Trebbiano d'Abruzzo",
    producer: "Valentini",
    region: "Abruzzo",
    country: "Italien",
    type: "Vitt",
    grapes: "Trebbiano d'Abruzzo",
  },
  {
    rank: 40,
    wine: "Saint-Joseph Sainte-Épine",
    producer: "Hervé Souhaut / Romaneaux-Destezet",
    region: "Saint-Jean-de-Muzols, Saint-Joseph, Rhône",
    country: "Frankrike",
    type: "Rött",
    grapes: "Syrah",
  },
  {
    rank: 41,
    wine: "Le Clos de la Tour de Curon",
    producer: "Bénédicte & Stéphane Tissot",
    region: "Arbois, Jura",
    country: "Frankrike",
    type: "Vitt",
    grapes: "Chardonnay",
  },
  {
    rank: 42,
    wine: "Macchiona",
    producer: "La Stoppa",
    region: "Emilia-Romagna",
    country: "Italien",
    type: "Rött",
    grapes: "Barbera, Bonarda",
  },
  {
    rank: 43,
    wine: "MunJebel Rosso",
    producer: "Cornelissen",
    region: "Etna, Sicilien",
    country: "Italien",
    type: "Rött",
    grapes: "Nerello Mascalese",
  },
  {
    rank: 44,
    wine: "Cuvée du Goulté",
    producer: "Marie-Noëlle Ledru",
    region: "Ambonnay Grand Cru, Champagne",
    country: "Frankrike",
    type: "Champagne",
    grapes: "Pinot Noir",
  },
  {
    rank: 45,
    wine: "Montepulciano d'Abruzzo",
    producer: "Valentini",
    region: "Abruzzo",
    country: "Italien",
    type: "Rött",
    grapes: "Montepulciano",
  },
  {
    rank: 46,
    wine: "Vouvray Pétillant Brut",
    producer: "Domaine Huet",
    region: "Vouvray, Loire",
    country: "Frankrike",
    type: "Mousserande",
    grapes: "Chenin Blanc",
  },
  {
    rank: 47,
    wine: "La Closerie Les Béguines",
    producer: "Jérôme Prévost / La Closerie",
    region: "Gueux, Montagne de Reims, Champagne",
    country: "Frankrike",
    type: "Champagne",
    grapes: "Pinot Meunier, Pinot Gris, Chardonnay",
  },
  {
    rank: 48,
    wine: "Viognier Romaneaux-Destezet",
    producer: "Hervé Souhaut",
    region: "Ardèche",
    country: "Frankrike",
    type: "Vitt",
    grapes: "Viognier",
  },
  {
    rank: 49,
    wine: "Morgon Vieilles Vignes",
    producer: "Guy Breton",
    region: "Beaujolais",
    country: "Frankrike",
    type: "Rött",
    grapes: "Gamay",
  },
  {
    rank: 50,
    wine: "Sagrantino di Montefalco",
    producer: "Paolo Bea",
    region: "Umbria",
    country: "Italien",
    type: "Rött",
    grapes: "Sagrantino",
  },
  {
    rank: 51,
    wine: "Les Vieilles Vignes des Blanderies",
    producer: "Mark Angeli / Ferme de la Sansonnière",
    region: "Thouarcé, Anjou, Loire",
    country: "Frankrike",
    type: "Vitt",
    grapes: "Chenin Blanc",
  },
  {
    rank: 52,
    wine: "Les Vignes d'Autrefois",
    producer: "Laherte Frères",
    region: "Chavot, Coteaux Sud d'Épernay, Champagne",
    country: "Frankrike",
    type: "Champagne",
    grapes: "Pinot Meunier",
  },
  {
    rank: 53,
    wine: "Cerasuolo d'Abruzzo",
    producer: "Valentini",
    region: "Abruzzo",
    country: "Italien",
    type: "Rosé",
    grapes: "Montepulciano",
  },
  {
    rank: 54,
    wine: "Les Vignes de Montgueux",
    producer: "Jacques Lassaigne / Emmanuel Lassaigne",
    region: "Montgueux, Aube, Champagne",
    country: "Frankrike",
    type: "Champagne",
    grapes: "Chardonnay",
  },
  {
    rank: 55,
    wine: "Brouilly Vieilles Vignes",
    producer: "Jean-Claude Lapalu",
    region: "Saint-Étienne-la-Varenne, Brouilly, Beaujolais",
    country: "Frankrike",
    type: "Rött",
    grapes: "Gamay",
  },
  {
    rank: 56,
    wine: "Vino Rosso San Valentino",
    producer: "Paolo Bea",
    region: "Umbria",
    country: "Italien",
    type: "Rött",
    grapes: "Sangiovese, Montepulciano, Sagrantino",
  },
  {
    rank: 57,
    wine: "Le Garde-Corps",
    producer: "Philippe Bornard",
    region: "Arbois-Pupillin, Jura",
    country: "Frankrike",
    type: "Rött",
    grapes: "Trousseau",
  },
  {
    rank: 58,
    wine: "La Lune",
    producer: "Mark Angeli / Ferme de la Sansonnière",
    region: "Thouarcé, Anjou, Loire",
    country: "Frankrike",
    type: "Vitt",
    grapes: "Chenin Blanc",
  },
  {
    rank: 59,
    wine: "Serragghia Zibibbo Bianco",
    producer: "Gabrio Bini / Serragghia",
    region: "Pantelleria, Sicilien",
    country: "Italien",
    type: "Vitt",
    grapes: "Zibibbo (Muscat d'Alexandrie)",
  },
  {
    rank: 60,
    wine: "Lunar",
    producer: "Movia",
    region: "Brda, Slovenien",
    country: "Slovenien",
    type: "Orange",
    grapes: "Rebula",
  },
  {
    rank: 61,
    wine: "Trousseau Les Grands Vergers",
    producer: "Michel Gahier",
    region: "Montigny-les-Arsures, Arbois, Jura",
    country: "Frankrike",
    type: "Rött",
    grapes: "Trousseau",
  },
  {
    rank: 62,
    wine: "Fac-Simile",
    producer: "Jérôme Prévost / La Closerie",
    region: "Gueux, Montagne de Reims, Champagne",
    country: "Frankrike",
    type: "Rosé",
    grapes: "Pinot Meunier",
  },
  {
    rank: 63,
    wine: "Fou du Roi",
    producer: "Axel Prüfer / Le Temps des Cerises",
    region: "Le Bousquet-d'Orb, Haut-Languedoc, Hérault",
    country: "Frankrike",
    type: "Rött",
    grapes: "Grenache, Cinsault, Carignan",
  },
  {
    rank: 64,
    wine: "Puro",
    producer: "Movia",
    region: "Brda, Slovenien",
    country: "Slovenien",
    type: "Mousserande",
    grapes: "Chardonnay, Pinot Noir",
  },
  {
    rank: 65,
    wine: "Riesling Grand Cru Steinert",
    producer: "Pierre Frick",
    region: "Alsace",
    country: "Frankrike",
    type: "Vitt",
    grapes: "Riesling",
  },
  {
    rank: 66,
    wine: "Le Mont Benoit Extra Brut",
    producer: "Emmanuel Brochet",
    region: "Villers-Aux-Noeuds, Montagne de Reims, Champagne",
    country: "Frankrike",
    type: "Champagne",
    grapes: "Pinot Meunier, Pinot Noir, Chardonnay",
  },
  {
    rank: 67,
    wine: "Dorabella Poulsard",
    producer: "L'Octavin / Alice Bouvot",
    region: "Arbois, Jura",
    country: "Frankrike",
    type: "Rött",
    grapes: "Poulsard",
  },
  {
    rank: 68,
    wine: "Les Lendemains qui Chantent",
    producer: "Axel Prüfer / Le Temps des Cerises",
    region: "Le Bousquet-d'Orb, Haut-Languedoc, Hérault",
    country: "Frankrike",
    type: "Rött",
    grapes: "Grenache",
  },
  {
    rank: 69,
    wine: "Trauben, Liebe und Zeit",
    producer: "Franz Strohmeier",
    region: "Weststeiermark, Österrike",
    country: "Österrike",
    type: "Mousserande",
    grapes: "Blauer Wildbacher",
  },
  {
    rank: 70,
    wine: "Roc d'Anglade Rouge",
    producer: "Rémy Pédreno",
    region: "Gard, Languedoc",
    country: "Frankrike",
    type: "Rött",
    grapes: "Carignan, Syrah, Grenache, Mourvèdre",
  },
  {
    rank: 71,
    wine: "Chinuri Pétillant Naturel",
    producer: "Iago Bitarishvili",
    region: "Kartli, Georgien",
    country: "Georgien",
    type: "Mousserande",
    grapes: "Chinuri",
  },
  {
    rank: 72,
    wine: "Arboreus",
    producer: "Paolo Bea",
    region: "Montefalco, Umbria",
    country: "Italien",
    type: "Vitt",
    grapes: "Trebbiano Spoletino",
  },
  {
    rank: 73,
    wine: "Le Cotet",
    producer: "Jacques Lassaigne / Emmanuel Lassaigne",
    region: "Montgueux, Aube, Champagne",
    country: "Frankrike",
    type: "Champagne",
    grapes: "Chardonnay",
  },
  {
    rank: 74,
    wine: "Pinot Gris Macération",
    producer: "Pierre Frick",
    region: "Pfaffenheim, Alsace",
    country: "Frankrike",
    type: "Orange",
    grapes: "Pinot Gris",
  },
  {
    rank: 75,
    wine: "Melon La Fauquette",
    producer: "Michel Gahier",
    region: "Montigny-les-Arsures, Arbois, Jura",
    country: "Frankrike",
    type: "Vitt",
    grapes: "Melon à Queue Rouge",
  },
  {
    rank: 76,
    wine: "Muntada",
    producer: "Domaine Gauby / Gérard & Lionel Gauby",
    region: "Calce, Roussillon",
    country: "Frankrike",
    type: "Rött",
    grapes: "Grenache, Carignan",
  },
  {
    rank: 77,
    wine: "Theodora",
    producer: "Gut Oggau",
    region: "Oggau, Burgenland, Österrike",
    country: "Österrike",
    type: "Vitt",
    grapes: "Grüner Veltliner, Welschriesling",
  },
  {
    rank: 78,
    wine: "Pinot Noir En Billat",
    producer: "Jean-François Ganevat",
    region: "Grusse, Côtes du Jura",
    country: "Frankrike",
    type: "Rött",
    grapes: "Pinot Noir",
  },
  {
    rank: 79,
    wine: "Matassa Rouge",
    producer: "Domaine Matassa / Tom Lubbe",
    region: "Calce, Roussillon",
    country: "Frankrike",
    type: "Rött",
    grapes: "Lledoner Pelut",
  },
  {
    rank: 80,
    wine: "Ploussard En Aspis",
    producer: "Renaud Bruyère & Adeline Houillon",
    region: "Arbois-Pupillin, Jura",
    country: "Frankrike",
    type: "Rött",
    grapes: "Ploussard",
  },
  {
    rank: 81,
    wine: "Blaufränkisch Mechthild",
    producer: "Gut Oggau",
    region: "Burgenland, Österrike",
    country: "Österrike",
    type: "Rött",
    grapes: "Blaufränkisch",
  },
  {
    rank: 82,
    wine: "Jakot",
    producer: "Dario Prinčič",
    region: "Oslavia, Friuli Collio",
    country: "Italien",
    type: "Orange",
    grapes: "Friulano (Jakot)",
  },
  {
    rank: 83,
    wine: "Riesling Pündericher Marienburg",
    producer: "Clemens Busch",
    region: "Mosel, Tyskland",
    country: "Tyskland",
    type: "Vitt",
    grapes: "Riesling",
  },
  {
    rank: 84,
    wine: "Les Tourillons",
    producer: "Renaud Bruyère & Adeline Houillon",
    region: "Arbois, Jura",
    country: "Frankrike",
    type: "Vitt",
    grapes: "Chardonnay, Savagnin",
  },
  {
    rank: 85,
    wine: "Riesling Cuvée Particulière",
    producer: "Domaine Gérard Schueller & Fils / Bruno Schueller",
    region: "Husseren-les-Châteaux, Alsace",
    country: "Frankrike",
    type: "Vitt",
    grapes: "Riesling",
  },
  {
    rank: 86,
    wine: "Larmande",
    producer: "Le Mazel / Gérald & Jocelyne Oustric",
    region: "Valvignères, Ardèche",
    country: "Frankrike",
    type: "Rött",
    grapes: "Syrah",
  },
  {
    rank: 87,
    wine: "Lousas Parcela Camino Novo",
    producer: "Envinate",
    region: "Amandi, Ribeira Sacra, Galicien",
    country: "Spanien",
    type: "Rött",
    grapes: "Mencía, Garnacha Tintorera",
  },
  {
    rank: 88,
    wine: "Ex Vero III",
    producer: "Werlitsch / Ewald Tscheppe",
    region: "Südsteiermark, Österrike",
    country: "Österrike",
    type: "Vitt",
    grapes: "Sauvignon Blanc, Morillon (Chardonnay)",
  },
  {
    rank: 89,
    wine: "Barolo",
    producer: "Bartolo Mascarello / Maria Teresa Mascarello",
    region: "Barolo, Piemonte",
    country: "Italien",
    type: "Rött",
    grapes: "Nebbiolo",
  },
  {
    rank: 90,
    wine: "Mademoiselle M",
    producer: "Alexandre Bain",
    region: "Tracy-sur-Loire, Pouilly-Fumé, Loire",
    country: "Frankrike",
    type: "Vitt",
    grapes: "Sauvignon Blanc",
  },
  {
    rank: 91,
    wine: "Empreinte",
    producer: "Benoît Courault",
    region: "Faye d'Anjou, Anjou, Loire",
    country: "Frankrike",
    type: "Vitt",
    grapes: "Chenin Blanc",
  },
  {
    rank: 92,
    wine: "Faugères Jadis",
    producer: "Domaine Léon Barral / Didier Barral",
    region: "Lenthéric, Faugères, Languedoc",
    country: "Frankrike",
    type: "Rött",
    grapes: "Carignan, Grenache, Syrah",
  },
  {
    rank: 93,
    wine: "Les Hautes Vignes",
    producer: "Emmanuel Brochet",
    region: "Villers-Aux-Noeuds, Montagne de Reims, Champagne",
    country: "Frankrike",
    type: "Champagne",
    grapes: "Chardonnay, Pinot Meunier",
  },
  {
    rank: 94,
    wine: "Le Feu",
    producer: "Domaine Belluard",
    region: "Ayse, Savoie",
    country: "Frankrike",
    type: "Vitt",
    grapes: "Gringet",
  },
  {
    rank: 95,
    wine: "Auksinis",
    producer: "Sébastien Riffault",
    region: "Sury-en-Vaux, Sancerre, Loire",
    country: "Frankrike",
    type: "Vitt",
    grapes: "Sauvignon Blanc",
  },
  {
    rank: 96,
    wine: "Schiste Blanc",
    producer: "Domaine des Ardoisières / Brice Omont",
    region: "Coteaux de Cévins, Savoie",
    country: "Frankrike",
    type: "Vitt",
    grapes: "Jacquère, Roussanne, Pinot Gris, Mondeuse Blanche",
  },
  {
    rank: 97,
    wine: "Nuits-Saint-Georges Clos des Corvées",
    producer: "Prieuré Roch",
    region: "Bourgogne",
    country: "Frankrike",
    type: "Rött",
    grapes: "Pinot Noir",
  },
  {
    rank: 98,
    wine: "Riesling Grand Cru Pfersigberg",
    producer: "Domaine Gérard Schueller & Fils / Bruno Schueller",
    region: "Husseren-les-Châteaux, Alsace",
    country: "Frankrike",
    type: "Vitt",
    grapes: "Riesling",
  },
  {
    rank: 99,
    wine: "Palo Blanco",
    producer: "Envinate",
    region: "Valle de La Orotava, Tenerife, Kanarieöarna",
    country: "Spanien",
    type: "Vitt",
    grapes: "Listán Blanco",
  },
  {
    rank: 100,
    wine: "Cailloux",
    producer: "Patrick Bouju / La Bohème",
    region: "Puy-de-Dôme, Auvergne",
    country: "Frankrike",
    type: "Rött",
    grapes: "Pinot Noir",
  },
];