/**
 * Shared Disallow paths for pactwines.com and dirtywine.se robots.txt.
 * Keep meta noindex on these routes too — Disallow alone is not enough.
 */
export const ROBOTS_DISALLOW_PATHS = [
  "/admin",
  "/admin-auth",
  "/api/",
  "/checkout",
  "/cart",
  "/access-request",
  "/access-pending",
  "/profile",
  "/log-in",
  "/login",
  "/signup",
  "/code-signup",
  "/invite-signup",
  "/producers/signup",
  "/producenter/signup",
  "/reset-password",
  "/forgot-password",
  "/auth/",
  "/taste-quiz",
  "/tasting/",
  "/pallet/",
  "/i/",
  "/ib/",
  "/b/",
  "/p/",
  "/c/",
  "/onboarding",
  "/settings",
  "/strategy-map",
  "/map-topo",
  "/wine-identity",
  "/reservation-status",
  "/dev",
  "/payment/",
] as const;
